---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: '{{ .Values.ISTIO_PUBLIC_GATEWAY_NAME }}'
  annotations:
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-weight: "-100"
    helm.sh/hook-delete-policy: "before-hook-creation"
spec:
  gatewayClassName: istio
  listeners:
  - name: default
    port: 8080
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: '{{ .Values.ISTIO_PRIVATE_GATEWAY_NAME }}'
  annotations:
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-weight: "-100"
    helm.sh/hook-delete-policy: "before-hook-creation"
spec:
  gatewayClassName: istio
  listeners:
  - name: default
    port: 8080
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All