---
kind: Service
apiVersion: v1
metadata:
    name: '{{ .Values.PUBLIC_SERVICE_NAME }}'
    annotations:
      helm.sh/hook: "post-install, post-upgrade"
      helm.sh/hook-weight: "110"
      helm.sh/hook-delete-policy: "before-hook-creation"
spec:
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    gateway.networking.k8s.io/gateway-name: '{{ .Values.ISTIO_PUBLIC_GATEWAY_NAME }}'
  clusterIP: None
  clusterIPs:
    - None
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster 
---
kind: Service
apiVersion: v1
metadata:
    name: '{{ .Values.PRIVATE_SERVICE_NAME }}'
    annotations:
      helm.sh/hook: "post-install, post-upgrade"
      helm.sh/hook-weight: "110"
      helm.sh/hook-delete-policy: "before-hook-creation"
spec:
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    gateway.networking.k8s.io/gateway-name: '{{ .Values.ISTIO_PRIVATE_GATEWAY_NAME }}'
  clusterIP: None
  clusterIPs:
    - None
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster 