apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: '{{ .Values.PRIVATE_GW_ROUTE_NAME }}'
spec:
  parentRefs:
  - name: '{{ .Values.ISTIO_PRIVATE_GATEWAY_NAME }}'
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: '{{ .Values.PRIVATE_FB_SERVICE_NAME }}'
      port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: '{{ .Values.PUBLIC_GW_ROUTE_NAME }}'
spec:
  parentRefs:
  - name: '{{ .Values.ISTIO_PUBLIC_GATEWAY_NAME }}'
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: '{{ .Values.PUBLIC_FB_SERVICE_NAME }}'
      port: 8080