---
kind: Service
apiVersion: v1
metadata:
    name: '{{ .Values.PUBLIC_FB_SERVICE_NAME }}'
    annotations:
        qubership.cloud/start.stage: '1'
    labels:
        name: '{{ .Values.PUBLIC_FB_SERVICE_NAME }}'
        app.kubernetes.io/name: '{{ .Values.PUBLIC_FB_SERVICE_NAME }}'
        app.kubernetes.io/part-of: 'Cloud-Core'
        app.kubernetes.io/managed-by: Helm
        deployment.qubership.org/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID }}'
spec:
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    name: public-frontend-gateway
  clusterIP: None
  clusterIPs:
    - None
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster 
---
kind: Service
apiVersion: v1
metadata:
    name: '{{ .Values.PRIVATE_FB_SERVICE_NAME }}'
    annotations:
        qubership.cloud/start.stage: '1'
    labels:
        name: '{{ .Values.PRIVATE_FB_SERVICE_NAME }}'
        app.kubernetes.io/name: '{{ .Values.PRIVATE_FB_SERVICE_NAME }}'
        app.kubernetes.io/part-of: 'Cloud-Core'
        app.kubernetes.io/managed-by: Helm
        deployment.qubership.org/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID }}'
spec:
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    name: private-frontend-gateway
  clusterIP: None
  clusterIPs:
    - None
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster 
