postgresPassword: ${POSTGRES_PASSWORD}

patroni:
  affinity:
    podAntiAffinity: {}
  replicas: ${PATRONI_REPLICAS_NUMBER}
  storage:
    storageClass: ${STORAGE_CLASS}
    size: 1Gi
  securityContext:
    fsGroup: 26
    runAsUser: 26